import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: {
    default: "Next js app",
    template: "%s | Next js app",
  },
  description:
    "Generated by create next app with n14 group teeacher Davron Raimjonov",
    openGraph: {
      images: ["/next.webp"]
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${montserrat.className} antialiased`}
      >
        <Navbar />
        {children}

        <footer className="bg-[red] mt-[100px] py-20 px-5">Footer</footer>
      </body>
    </html>
  );
}


/// company page | company name